### ISSUE TITLE
[Chapter page] Relocate toolbar to bottom of the page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/GATBReferenceGuide-Android#89]
# Goal
Reposition the toolbar to improve visibility

## Tasks
- [x] Add a 'Home' button to the toolbar which takes the user back to home page
- [x] Add 'Font' functionality
- [x] Font setting should be saved and stored internally on the app (similar to how it currently behaves in the settings page)
- [x] Font should change dynamically as user modifies it in the pop-up 
- [x] Min and max limits on the font size should be the same as in the settings page
- [x] Feedback button will be removed
- [x] Tab navigation should not be visible in the chapter or chart pages

## Out of scope
- Icon selection colors (i.e. bookmarks)
- Banner color
- Icon prefacing the chapter name 
- In-chapter search feature

![Image](https://github.com/AppHatchery/GATBReferenceGuide-Android/assets/16402216/41c3a32d-b5ad-47bc-b8a0-bbb77a415898)

![Image](https://github.com/AppHatchery/GATBReferenceGuide-Android/assets/16402216/eb8dd40d-6b65-4ae5-8c68-ec9b65c0e963)

For dimensions and references
https://www.figma.com/design/ZYZkodGKNJ3VOJMVlqdCMo/GA-TB-GUIDE-REDESIGN?node-id=2660-4413&t=BKQnGEhKHv8WzVxf-1
